### ISSUE TITLE
Migration from sass-lint

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/stylelint-config-torchbox#1]
## TODO

- [ ] [class-name-format](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/class-name-format.md) hyphenatedbem -> [selector-class-pattern](https://stylelint.io/user-guide/rules/selector-class-pattern), `! /[A-Z]|-{3}|_{3}|[^_]_[^_]/`, `resolveNestedSelectors: true`
- [ ] [mixin-name-format](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/mixin-name-format.md) hyphenatedlowercase -> [at-mixin-pattern](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-mixin-pattern/README.md) `! /[^\-a-z0-9]/`
- ~[bem-depth](https://github.com/sasstools/sass-lint/blob/master/docs/rules/bem-depth.md)~ – not valuable enough / can be spotted in code review
- ~[force-element-nesting](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/force-element-nesting.md)~ – this doesn’t seem valuable to enforce as a blanket rule

## Major differences / additions to review

We’ll add all of these for now, can revise if needed

- [x] id selectors are forbidden
- [x] `@extend` / placeholders are forbidden
- [x] `!important` is forbidden
- [x] Max nesting depth of 4 (before: no maximum)
- [x] Max element types per selector of 2 (with exceptions, https://stylelint.io/user-guide/rules/selector-max-type)\
- [x] Maximum specificity of `0,4,0`

## Migration progress

With old sass-lint config in red, new stylelint config in green:

```diff
# Won’t be enforced anymore.
-  bem-depth:
-    - 1
-    - max-depth: 2
# Completely disallow @extend
-  extends-before-mixins: 2
-  extends-before-declarations: 2
-  placeholder-in-extend: 2
+ 'scss/percent-placeholder-pattern': '^do-not-use-placeholders$',
# stylelint-config-prettier
-  empty-line-between-blocks:
-    - 2
-    - include: true
-    - allow-single-line-rulesets: false
# Done with stylelint-order
-  mixins-before-declarations:
-    - 2
-    - exclude:
-        - media-query
+ 'order/order': [
+     'dollar-variables',
+     'custom-properties',
+     // @-rules that have no nesting.
+     { type: 'at-rule', hasBlock: false },
+     'declarations',
+     'rules',
+     // @-rules that have nested elements, e.g. media queries
+     { type: 'at-rule', hasBlock: true },
+ ],
# Not enforced by stylelint.
-  no-warn: 0
-  no-debug: 0
# stylelint-config-prettier
-  indentation: 0
# Not enforced by stylelint.
-  variable-for-property:
-    - 0
# Not enforced by stylelint.
-  no-css-comments: 0
# TODO with a regex for selector-class-pattern.
  class-name-format:
    - 1
    - convention: hyphenatedbem
# Not enforced by styellint.
-   force-pseudo-nesting: 0
# Now enforced
-  nesting-depth: 0
+ 'max-nesting-depth': 4,
# Not enforced by styellint.
-  force-attribute-nesting: 0
- # This seems hard / impossible to enforce. Removing.
-  force-element-nesting: 1
# Not enforced
-  no-qualifying-elements: 0
# Done with number-leading-zero
-  leading-zero:
-    - 1
-    - include: true
+ 'number-leading-zero': 'always',
# Enforced with multiple rules
-  no-vendor-prefixes:
-    - 1
+ 'value-no-vendor-prefix': true,
+ 'property-no-vendor-prefix': true,
+ 'selector-no-vendor-prefix': true,
+ 'media-feature-name-no-vendor-prefix': true,
+ 'at-rule-no-vendor-prefix': true,
# TODO
  mixin-name-format:
    - 1
    - convention: hyphenatedlowercase
# Now enforced.
-  no-color-keywords: 0
+ 'color-named': 'never',
# Not enforced by stylelint.
-  no-color-literals: 0
# Not enforced by stylelint.
-  property-sort-order: 0
# Enforced with stylelint-scss
-  empty-args:
-    - 1
-    - include: true
+ 'scss/at-mixin-argumentless-call-parentheses': 'always',
```

## Base `sass-lint` config

```yaml
  bem-depth:
    - 1
    - max-depth: 2
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  empty-line-between-blocks:
    - 2
    - include: true
    - allow-single-line-rulesets: false
  mixins-before-declarations:
    - 2
    - exclude:
        - media-query
  no-warn: 0
  no-debug: 0
  indentation: 0
  variable-for-property:
    - 0
  no-css-comments: 0
  class-name-format:
    - 1
    - convention: hyphenatedbem
  force-pseudo-nesting: 0
  nesting-depth: 0
  force-attribute-nesting: 0
  force-element-nesting: 1
  no-qualifying-elements: 0
  leading-zero:
    - 1
    - include: true
  no-vendor-prefixes:
    - 1
  mixin-name-format:
    - 1
    - convention: hyphenatedlowercase
  no-color-keywords: 0
  no-color-literals: 0
  property-sort-order: 0
  empty-args:
    - 1
    - include: true
```
